#!/usr/bin/python3
import sys

def factorize_nums(number):
	for i in range(1, number + 1):
		if number % i == 0 and i is not 1:
			return i


def factorize_file(file_name):
	with open(file_name, 'r') as file:
		for line in file:
			num = int(line)
			result = factorize_nums(num)
			print ("{}={}*{}".format(num, int(num / result), result))
	file.close()

if __name__ == "__main__":

    if len(sys.argv) != 2:
        sys.exit("Usage: factor <file>")
    factorize_file(sys.argv[1])
